---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm ci
        npm run build

    # - name: Test
    #   run: npm run test

    - name: Deploy
      run: |
        git config --global user.name 'Anderson Guedes'
        git config --global user.email 'anderson.guedes@outlook.com.br'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy